#%RAML 1.0 DataType
type: object
properties:
  client_id: string
  sf_client_id: string
  name: string
  first_name: string
  middle_name": string
  last_name: string
  birth_date: string
  phone: string
  email: string
  shipping_street: string
  shipping_city: string
  shipping_country: string
  shipping_state: string
  shipping_postalcode: number
  annual_income: string
  citizenship: string