#%RAML 1.0 DataType
properties:
  accountId: number
  subAccountId: number
  validityDate: string
  currentAssetValueAmount: string
  totalInvestmentAmount: string
  totalWithdrawnAmount: string
  totalIncomeAmount: string
  encashmentValueAmount: string
  bankingBalanceAmount: string
  netChange: string