#%RAML 1.0 NamedExample
value:
  client_id: "111222333"
  sf_client_id: "aaa33449rnidofv"
  name: "Robert B Ross"
  first_name: "Robert"
  middle_name": "Bob"
  last_name: "Ross"
  birth_date: "6-12-1989"
  phone: "111-222-3333"
  email: "e@mail.com"
  shipping_street: "string"
  shipping_city: "string"
  shipping_country: "US"
  shipping_state: "CA"
  shipping_postalcode: 112233
  annual_income: "$700,000"
  citizenship: "yes"